### PR TITLE
Expose multiple ways to create a sequence number

### PR DESCRIPTION
**Pull request by irevoire**
Hey, it's a bit boring to work with the sequential number of this lib because their formatting is really important in order to retrieve them, but we can't create a sequence number ourselves.
This means I must think at all times of formatting it myself when I want to get something:
```rust
let task_id_string = format!("/tasks/task-{:0>10?}", task_id);
```

It would be nice if we had a way to create them ourselves like that;
```rust
let task_id_string = format!("/tasks/task-{}", Sequence::from(task_id));
```

---

Also, another thing, `CreateSequence` was a good name when we couldn't return it. If you are interested in merging this PR, maybe we should rename it to something more versatile like `Sequence` or `SequenceNumber`, but that's a breaking change. What do you think?

### CODE REVIEW

**Comment by irevoire** [comment]
I want the opposite actually.

My use case was, for example: I get this sequence number. I write it in a file. Later on, I deserialize it from whatever format I used and I can't use your display implementation.

**Comment by kezhuw** [comment]
I see your case and think a custom type, say think wrapper around `String`, could solve it.

The library itself does not accept `CreateSequence` as input parameter of any methods, so exposing creation of `CreateSequence` has no means to the library. `CreateSequence` expose two properties:
1. Order comparison.
2. String format.

The two could be easily achieved by wrapping custom type around result `String` from formatting of `CreateSequence`.

**Comment by irevoire** [comment]
If I do that, then I can't do any operations on the ID, so it wasn't really a solution in my case.
But I understand that you don't want to implement a solution for it, and I stopped using zookeeper, so I'm going to close your PR.

**Comment by kezhuw** [comment]
Close as the library itself does not accept `CreateSequence` as input parameter of any methods and exposing creation of `CreateSequence` has no means to the library.

Thank for your inputs and patience!

**Pull request closed without merging**
